<a href="https://colab.research.google.com/github/tejuuu-7774/DVA_Collabs/blob/main/DVA_LEC_13_SKELETON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lecture 13: Data Filtering, Grouping, Merging & Pivoting in Pandas

**Dataset:** Custom car dataset (in-memory, intentionally clean)  
**Focus:** Filtering, grouping, and merging logic using Pandas

## Before We Begin

In this lecture, we will focus on **data manipulation logic**, not data cleaning.

The dataset is intentionally clean so we can concentrate on:
- Filtering rows using conditions  
- Summarizing data using grouping and aggregation  
- Combining datasets using joins  

> If you are looking for missing values, duplicates, or preprocessing steps, those are out of scope for this lecture.

## Dataset Setup

We will work with a custom car dataset created directly in the notebook.
This avoids external file dependencies and keeps the focus on logic.

In [ ]:
import pandas as pd

In [ ]:
# Custom dataset for Lecture 13
# This dataset is intentionally clean to focus on filtering, grouping, and merging logic

data = {
    'Price': [12000, 15000, 9000, 18000, 22000, 14000, 16000, 8000, 20000, 17000,
              11000, 13000, 21000, 9500, 15500, 14500, 16500, 18500, 12500, 17500,
              25000, 35000],

    'Age': [5, 3, 12, 2, 1, 6, 4, 15, 2, 3,
            8, 7, 1, 14, 4, 6, 5, 2, 9, 3, 2, 4],

    'KM': [50000, 30000, 90000, 20000, 10000, 60000, 45000, 120000, 15000, 25000,
           70000, 65000, 8000, 110000, 48000, 58000, 52000, 22000, 75000, 27000,
           10000, 20000],

    'FuelType': ['Petrol', 'Diesel', 'Petrol', 'Diesel', 'Hybrid',
                 'Petrol', 'Diesel', 'Petrol', 'Hybrid', 'Diesel',
                 'Petrol', 'Petrol', 'Hybrid', 'Diesel', 'Petrol',
                 'Diesel', 'Petrol', 'Hybrid', 'Diesel', 'Petrol',
                 'Electric', 'Electric'],

    'HP': [90, 110, 85, 120, 130, 95, 105, 80, 140, 115,
           92, 98, 135, 88, 108, 102, 100, 125, 96, 112,
           100, 96],

    'Automatic': [0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
                  0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
                  0, 1],

    'Doors': [4, 4, 3, 4, 5, 4, 4, 3, 5, 4,
              4, 4, 5, 3, 4, 4, 4, 5, 4, 4,
              4, 5],

    'Weight': [1100, 1200, 1050, 1300, 1400, 1150, 1250, 1000, 1450, 1350,
               1120, 1180, 1420, 1080, 1230, 1210, 1190, 1380, 1160, 1320,
               1000, 1150]
}

df = pd.DataFrame(data)

In [ ]:
# Let's analyze the first 5 columns
df.head()

   Price  Age     KM FuelType   HP  Automatic  Doors  Weight
0  12000    5  50000   Petrol   90          0      4    1100
1  15000    3  30000   Diesel  110          1      4    1200
2   9000   12  90000   Petrol   85          0      3    1050
3  18000    2  20000   Diesel  120          1      4    1300
4  22000    1  10000   Hybrid  130          1      5    1400

#### Fun fact: .shape an attribute that only returns tuple, and not a function. That's why we won't be using **()**

In [ ]:
df.shape

(22, 8)

In [ ]:
df.columns

Index(['Price', 'Age', 'KM', 'FuelType', 'HP', 'Automatic', 'Doors', 'Weight'], dtype='object')

At a high level, this dataset contains:
- Numeric attributes (Price, Age, KM, HP, Weight)
- Categorical attributes (FuelType, Doors)
- Boolean-like attributes (Automatic: 0 = Manual, 1 = Automatic)

## 1. Why Do We Need Filtering and Grouping?

Consider the following question:

> How can we identify cars that are Petrol, older than 10 years, and cost less than 10,000?

Looking at raw rows does not scale.

First, we need a **systematic way to filter relevant rows**.  
Later, we’ll see how grouping and aggregation help us **summarize** the results.

When we filter data, we create a condition that evaluates to either True or False for each row.
Rows where the condition is True are kept.

## 2.1 Single-Condition Filtering

Filtering allows us to select rows that satisfy a specific condition.

At a conceptual level:
- We define a condition on a column
- That condition is evaluated for every row
- Rows where the condition is `True` are kept

In [ ]:
# Filter cars with Price greater than 15000
df = df[df['Price'] > 15000]

In [ ]:
# What happens internally:
# df['Price'] > 15000 returns a Boolean Series (True / False for each row)
# Rows where the condition is True are retained in the result

### 2.2 Filtering with `.loc[]`

The `.loc[]` accessor allows us to filter rows and select columns together.

In [ ]:
# Using .loc[] to filter rows and select specific columns

Key takeaway:
- Filtering in Pandas is row-based
- Conditions are evaluated for every row
- Boolean indexing is the foundation for all advanced filtering operations

>So far, we have applied only one condition.
Next, we’ll see how to combine multiple conditions together.

### 2.3 Multi-Condition Filtering

When combining conditions, **parentheses are critical**.

Each condition must be evaluated correctly before combining them using:
- AND (`&`)
- OR (`|`)

In [ ]:
# Multi-condition filtering using AND (&)
# Parentheses are REQUIRED around each condition
df = df[(df['Price'] > 10000) & (df['FuelType']=='Petrol')]
df

    Price  Age     KM FuelType   HP  Automatic  Doors  Weight
0   12000    5  50000   Petrol   90          0      4    1100
5   14000    6  60000   Petrol   95          0      4    1150
10  11000    8  70000   Petrol   92          0      4    1120
11  13000    7  65000   Petrol   98          0      4    1180
14  15500    4  48000   Petrol  108          1      4    1230
16  16500    5  52000   Petrol  100          0      4    1190
19  17500    3  27000   Petrol  112          1      4    1320

In [ ]:
# Multi-condition filtering using OR (|)
# A row is kept if ANY condition evaluates to True
df = df[(df['Price'] > 20000) | (df['FuelType']=='Diesel')]
df

    Price  Age      KM  FuelType   HP  Automatic  Doors  Weight
1   15000    3   30000    Diesel  110          1      4    1200
3   18000    2   20000    Diesel  120          1      4    1300
4   22000    1   10000    Hybrid  130          1      5    1400
6   16000    4   45000    Diesel  105          1      4    1250
9   17000    3   25000    Diesel  115          1      4    1350
12  21000    1    8000    Hybrid  135          1      5    1420
13   9500   14  110000    Diesel   88          0      3    1080
15  14500    6   58000    Diesel  102          1      4    1210
18  12500    9   75000    Diesel   96          0      4    1160
20  25000    2   10000  Electric  100          0      4    1000
21  35000    4   20000  Electric   96          1      5    1150

#### Common Mistake  
Using `and` / `or` instead of `&` / `|` when filtering Pandas DataFrames.
We’ll see the correct way to combine conditions next.

**Important rules when combining conditions:**
- Always wrap each condition in parentheses
- Use `&` for AND, `|` for OR
- Never use `and` / `or` with Pandas Series

These rules apply everywhere filtering is used in Pandas.

>So far, we’ve combined conditions using logical operators.
Next, we’ll look at a cleaner way to filter for multiple categorical values.

### 2.4 Filtering Using `.isin()`

When filtering for multiple categorical values, `.isin()` provides a clean and readable solution.

In [ ]:
df[df['Doors'].isin([3, 5])]

    Price  Age      KM  FuelType   HP  Automatic  Doors  Weight
2    9000   12   90000    Petrol   85          0      3    1050
4   22000    1   10000    Hybrid  130          1      5    1400
7    8000   15  120000    Petrol   80          0      3    1000
8   20000    2   15000    Hybrid  140          1      5    1450
12  21000    1    8000    Hybrid  135          1      5    1420
13   9500   14  110000    Diesel   88          0      3    1080
17  18500    2   22000    Hybrid  125          1      5    1380
21  35000    4   20000  Electric   96          1      5    1150

`.isin()` improves readability when filtering for multiple values in a column.

Use `.isin()` when:
- You have multiple acceptable values
- The column is categorical or discrete
- You want cleaner and more readable code

> We’ve now seen how to filter data using single conditions,
multiple conditions, and categorical membership.

### Checkpoint 1 (Student Task)

Write the code to find the **number of cars** that are:
- Automatic  
**OR**
- Have an Age greater than 10 years

In [ ]:
# Condition 1: Automatic cars (1 = Automatic)
# Condition 2: Cars older than 10 years
# Use OR (|) to keep rows that satisfy either condition

Key takeaways:
- Use `|` for OR in Pandas
- Wrap each condition in parentheses
- Counting rows can be done using `filtered_df.shape[0]`

## 3. Grouping Data for Summary Analysis

So far, filtering helped us answer:
- Which rows are relevant?

However, filtering still returns **individual rows**.

In many scenarios, we want **summary-level answers**, such as:
- What is the average price per fuel type?
- How does mileage vary across categories?

For this, we use **grouping**.

### 3.1 The Split–Apply–Combine Pattern

Grouping in Pandas follows a three-step process:

1. **Split** the data into groups based on a key  
2. **Apply** a function to each group  
3. **Combine** the results into a new DataFrame

> All groupby operations we see next follow this exact pattern.

### 3.2 Grouping by a Single Column

Let’s calculate summary statistics grouped by fuel type.

In [ ]:
# Grouping by FuelType and calculating the average Price
df.groupby('FuelType')['Price'].mean()

FuelType
Diesel      14642.857143
Electric    30000.000000
Hybrid      20375.000000
Petrol      12944.444444
Name: Price, dtype: float64

What happened here:
- The data was split by `FuelType`
- The mean Price was calculated for each group
- The result is a summary indexed by FuelType

Optional Note:
- The grouping column (`FuelType`) becomes the index by default
- This is expected behavior in Pandas

### 3.3 Aggregating Multiple Metrics

In many real-world scenarios, a single summary metric is not sufficient.

For example, for each fuel type, we may want to know:
- How many cars exist
- The average price
- The maximum mileage observed

Pandas allows us to compute multiple aggregations at once using `.agg()`.

In [ ]:
# Aggregating multiple metrics for each FuelType
df.groupby('FuelType').agg({'Price': 'mean', 'KM': 'max', 'Doors': 'count'})

                 Price      KM  Doors
FuelType
Diesel    14642.857143  110000      7
Electric  30000.000000   20000      2
Hybrid    20375.000000   22000      4
Petrol    12944.444444  120000      9

What this does:
- Groups the data by `FuelType`
- Computes multiple summary statistics per group
- Returns a structured, readable DataFrame

Using named aggregations helps make the output self-explanatory.

### 3.4 Grouping by Multiple Columns

Sometimes, one grouping key is not enough to answer analytical questions.

By grouping on multiple columns, we can create more granular summaries.

In [ ]:
# Grouping by multiple columns: FuelType and Doors
df.groupby(['FuelType', 'Doors'])['Price'].mean()

FuelType  Doors
Diesel    3         9500.000000
          4        15500.000000
Electric  4        25000.000000
          5        35000.000000
Hybrid    5        20375.000000
Petrol    3         8500.000000
          4        14214.285714
Name: Price, dtype: float64

This operation:
- Splits the data by FuelType first
- Then further splits each group by Doors
- Calculates the average price for each combination

The result uses a MultiIndex.
At this stage, focus on interpreting the values, not manipulating the index.

>Now that we can group and summarize data in multiple ways,
let’s test this understanding with a short exercise.

### Checkpoint 2 (Quiz)

Write the code to calculate the **total Weight** for each **Doors** category
and sort the result in **descending order of total Weight**.

In [ ]:
# Group by Doors and calculate total Weight
# Then sort the result in descending order
df.groupby('Doors')['Weight'].sum().sort_values(ascending=False)

Doors
4    16760
5     6800
3     3130
Name: Weight, dtype: int64

What this solution does:
- Groups the data by the number of Doors
- Sums the Weight for each group
- Sorts the results to identify which category contributes the most total weight

>So far, we’ve summarized data within a single table.
Next, we’ll look at how to combine information from multiple tables.

## 4. Why Do We Need Joins?

So far, all our analysis has been limited to a single table.

In real-world data systems, information is often split across
multiple tables to avoid duplication and maintain structure.

For example:
- One table may store car details
- Another table may store commission rates or dealer information

To analyze such data together, we need a way to **combine tables**.
This is where joins come in.

>When combining two tables, an important question is:
Which rows do we want to keep?

### 4.1 Join Concepts

In this lecture, we will focus on two join types:
- Inner Join
- Left Join

Before choosing a join type, always ask:

> Which rows do I want to keep?

### 4.2 Implementing a Left Join

A Left Join keeps **all rows from the left table**  
and brings in matching data from the right table when available.

If no matching data exists, the result contains missing values (`NaN`)
for the right table’s columns.

In [ ]:
# Create a small reference table with commission rates by FuelType
df_commission = pd.DataFrame({
    'FuelType': ['Petrol', 'Diesel', 'Hybrid', 'Electric'],
    'Commission_Rate': [0.0, 0.0, 0.0, 0.0]
})

In [ ]:
df_commission

   FuelType  Commission_Rate
0    Petrol              0.0
1    Diesel              0.0
2    Hybrid              0.0
3  Electric              0.0

In [ ]:
# Perform a Left Join
# All rows from df (left table) will be retained

df_left_joined = pd.merge(df, df_commission, on='FuelType', how='left')
df_left_joined

,Price,Age,KM,FuelType,HP,Automatic,Doors,Weight,Commission_Rate
0,12000,5,50000,Petrol,90,0,4,1100,0.0
1,15000,3,30000,Diesel,110,1,4,1200,0.0
2,9000,12,90000,Petrol,85,0,3,1050,0.0
3,18000,2,20000,Diesel,120,1,4,1300,0.0
4,22000,1,10000,Hybrid,130,1,5,1400,0.0
5,14000,6,60000,Petrol,95,0,4,1150,0.0
6,16000,4,45000,Diesel,105,1,4,1250,0.0
7,8000,15,120000,Petrol,80,0,3,1000,0.0
8,20000,2,15000,Hybrid,140,1,5,1450,0.0
9,17000,3,25000,Diesel,115,1,4,1350,0.0
10,11000,8,70000,Petrol,92,0,4,1120,0.0
11,13000,7,65000,Petrol,98,0,4,1180,0.0
12,21000,1,8000,Hybrid,135,1,5,1420,0.0
13,9500,14,110000,Diesel,88,0,3,1080,0.0
14,15500,4,48000,Petrol,108,1,4,1230,0.0
15,14500,6,58000,Diesel,102,1,4,1210,0.0
16,16500,5,52000,Petrol,100,0,4,1190,0.0
17,18500,2,22000,Hybrid,125,1,5,1380,0.0
18,12500,9,75000,Diesel,96,0,4,1160,0.0
19,17500,3,27000,Petrol,112,1,4,1320,0.0
20,25000,2,10000,Electric,100,0,4,1000,0.0
21,35000,4,20000,Electric,96,1,5,1150,0.0

What happened here:
- Each car row was matched to its FuelType in the commission table
- All cars were retained, regardless of whether a match existed
- Commission_Rate is added where a match was found

In [ ]:
# Verify that the number of rows remains unchanged

>Now let’s see what changes when we choose a different join type.

### 4.3 Contrasting Left Join and Inner Join

An Inner Join keeps **only rows that have a matching key in both tables**.

Unlike a Left Join, rows without a match are **dropped** from the result.

In [ ]:
# Perform an Inner Join
# Only rows with matching FuelType values in both tables are retained

>Choosing the correct join type depends on whether unmatched rows
should be preserved or discarded.

What changed:
- Only cars with a FuelType present in both tables are retained
- Cars without a matching FuelType are removed
- The total number of rows is reduced

This behavior is expected and intentional in an Inner Join.

### Checkpoint 3 (Conceptual)

You need to combine the car dataset with a table that contains
dealer ratings.

You want to **keep all cars**, even if a rating is missing.

Which parameter should you use in `pd.merge()` and why?

> Use `how='left'` in `pd.merge()`.A Left Join keeps all rows from the left table (car data) and includes matching rows from the right table when available.
If a rating is missing, the car is still retained with `NaN` values.

## 5. Why Do We Need Pivot Tables?

### Business Context

Imagine you are a Data Analyst at an e commerce company.

You are given transaction level data:
Each row is one transaction

*   Multiple regions
*   Multiple products
*   Different revenues

Now management asks:

* What is total revenue by region?
* What is revenue by region and product?
* Which product performs best in each region?
* Can we see it in a matrix form like Excel Pivot?

You can use **groupby()**.

But **groupby()** gives you a vertical output.

***Pivot gives you a structured business matrix.***

That is why pivot exists.

##**Step 5.1** Create Sample Dataset

In [ ]:
import pandas as pd

data = {
    "order_id": [1,2,3,4,5,6,7,8,9,10],
    "region": ["North","South","North","East","West","South","North","East","West","North"],
    "product": ["Laptop","Lapt op","Mobile","Laptop","Mobile","Mobile","Laptop","Mobile","Laptop","Mobile"],
    "revenue": [80000,90000,20000,75000,15000,30000,60000,5000,45000,25000]
}

df = pd.DataFrame(data)
df

   order_id region  product  revenue
0         1  North   Laptop    80000
1         2  South  Lapt op    90000
2         3  North   Mobile    20000
3         4   East   Laptop    75000
4         5   West   Mobile    15000
5         6  South   Mobile    30000
6         7  North   Laptop    60000
7         8   East   Mobile     5000
8         9   West   Laptop    45000
9        10  North   Mobile    25000

### Revenue by Region and Product

In [ ]:
df.groupby(["region","product"])["revenue"].sum()

region  product
East    Laptop      75000
        Mobile       5000
North   Laptop     140000
        Mobile      45000
South   Lapt op     90000
        Mobile      30000
West    Laptop      45000
        Mobile      15000
Name: revenue, dtype: int64

### **Step 5.2**: Solve Using groupby()

In [ ]:
df.groupby("region")["revenue"].sum()

region
East      80000
North    185000
South    120000
West      60000
Name: revenue, dtype: int64

#### The output is hierarchical and vertical.

### **Step 5.3**: The Business Need

Management wants something like this:
| Region | Laptop | Mobile |
|--------|--------|--------|
| North  |   ?    |   ?    |
| South  |   ?    |   ?    |

That structure does not naturally come from **groupby()**.

This is where Pivot Tables help.

## 6. Pivot Table in Pandas

### Basic Pivot Table

In [ ]:
pd.pivot_table(
    data=df,
    index="region",
    values="revenue",
    aggfunc="sum"
)

        revenue
region
East      80000
North    185000
South    120000
West      60000

Now we get a 2D matrix.

This is Python’s version of Google Sheets Pivot Table.

### 6.1 Handling Missing Values

Some combinations may not exist.

We can replace missing values using fill_value.

This makes the table cleaner for dashboards.

Multiple Aggregations

Suppose management wants:
*   Total Revenue
*   Average Revenue

#### Add Grand Totals (Like Google Sheets)

In [ ]:
pd.pivot_table(
    df,
    index="region",
    values="revenue",
    aggfunc=["sum","mean"],
    margins=True,
    margins_name="Total",
    fill_value=0
)

           sum     mean
       revenue  revenue
region
East     80000  40000.0
North   185000  46250.0
South   120000  60000.0
West     60000  30000.0
Total   445000  44500.0

This adds:
*   Total row
*   Total Column


*Very useful for reporting.*

## 7. Crosstab for Categorical Analysis

Pivot is for numerical aggregation.

Crosstab is useful for counting category combinations.

**Count of Transactions**

In [ ]:
pd.crosstab(
    index=df["region"],
    columns=df["product"],
    margins=True,
    margins_name="Total"
)

product  Lapt op  Laptop  Mobile  Total
region
East           0       1       1      2
North          0       2       2      4
South          1       0       1      2
West           0       1       1      2
Total          1       4       5     10

Now we can understand distribution patterns.

This is powerful for EDA.

## Summary

In this lecture, we focused on three core data manipulation skills:

### Filtering
- Selected relevant rows using logical conditions
- Combined conditions using `&`, `|`, and `.isin()`
- Built a clear mental model around Boolean indexing

### Grouping
- Moved from row-level data to summary-level insights
- Applied the split–apply–combine pattern
- Used `.agg()` and multi-column grouping to generate meaningful summaries

### Merging
- Combined data from multiple tables using joins
- Understood the practical difference between Left and Inner Joins
- Chose join types based on which rows should be preserved

### Pivot Tables & Cross Tabs
- *pivot_table()* creates business readable matrices
- *crosstab()* helps analyze category distribution

The key takeaway:
> Effective data analysis is about **asking the right questions**  
> and choosing the **correct operation** to answer them.

## Student Activities & Exercises

Refer to the exercise sheet for additional practice problems
covering filtering, grouping, and merging.

## Student Activities (In-Class)

### Activity 1: Filtering Practice
Using the dataset, filter all cars that:
- Are Diesel
- Have more than 100,000 KM

How many such cars exist?

In [ ]:
# Custom dataset for Lecture 13
# This dataset is intentionally clean to focus on filtering, grouping, and merging logic

data = {
    'Price': [12000, 15000, 9000, 18000, 22000, 14000, 16000, 8000, 20000, 17000,
              11000, 13000, 21000, 9500, 15500, 14500, 16500, 18500, 12500, 17500,
              25000, 35000],

    'Age': [5, 3, 12, 2, 1, 6, 4, 15, 2, 3,
            8, 7, 1, 14, 4, 6, 5, 2, 9, 3, 2, 4],

    'KM': [50000, 30000, 90000, 20000, 10000, 60000, 45000, 120000, 15000, 25000,
           70000, 65000, 8000, 110000, 48000, 58000, 52000, 22000, 75000, 27000,
           10000, 20000],

    'FuelType': ['Petrol', 'Diesel', 'Petrol', 'Diesel', 'Hybrid',
                 'Petrol', 'Diesel', 'Petrol', 'Hybrid', 'Diesel',
                 'Petrol', 'Petrol', 'Hybrid', 'Diesel', 'Petrol',
                 'Diesel', 'Petrol', 'Hybrid', 'Diesel', 'Petrol',
                 'Electric', 'Electric'],

    'HP': [90, 110, 85, 120, 130, 95, 105, 80, 140, 115,
           92, 98, 135, 88, 108, 102, 100, 125, 96, 112,
           100, 96],

    'Automatic': [0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
                  0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
                  0, 1],

    'Doors': [4, 4, 3, 4, 5, 4, 4, 3, 5, 4,
              4, 4, 5, 3, 4, 4, 4, 5, 4, 4,
              4, 5],

    'Weight': [1100, 1200, 1050, 1300, 1400, 1150, 1250, 1000, 1450, 1350,
               1120, 1180, 1420, 1080, 1230, 1210, 1190, 1380, 1160, 1320,
               1000, 1150]
}

df = pd.DataFrame(data)

In [ ]:
# Filter Diesel cars with KM > 100000

### Activity 2: Grouping Practice
Calculate the **average Price** of cars grouped by:
- FuelType

Which FuelType has the highest average price?

In [ ]:
# Average price by FuelType

In [ ]:
# FuelType with highest average price

## Post-Class Exercises

### Exercise 1: Filtering & Aggregation
Find the **average Price** of Petrol cars that:
- Are older than 5 years
- Have more than 50,000 KM

In [ ]:
# Filter Petrol cars with Age > 5 and KM > 50000


# Calculate average price

### Exercise 2: Grouping Analysis
Group the cars by the number of Doors and calculate:
- Mean Age
- Median Age

Based on the result, which door category is associated with newer cars?

In [ ]:
# Group by Doors and calculate mean and median Age

In [ ]:
# Door category with lowest mean age (newest cars)

### Exercise 3: Merging Practice
Create a small DataFrame called `df_rating` with:
- FuelType
- Dealer_Rating

Perform a Left Join between the car dataset and `df_rating`.

Why is a Left Join appropriate here?

In [ ]:
# Create dealer rating table

In [ ]:
# Perform Left Join to retain all cars

In [ ]:
# Verify that no rows were dropped